[programs.devnet]
myepicproject = "fG5CZ7DEsZrC2LVSeo7LutUu8xjvLoRyDRCjjWixQMj"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/kirso/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
